//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using SQLite.Net;
using SQLite.Net.Attributes;
using System;

namespace SQLiteExample
{
    public partial class MainTable
    {
        [PrimaryKey]
        public Int64 Id { get; set; }
        
        [NotNull]
        public String Name { get; set; }
        
        [NotNull]
        public DateTime StartTime { get; set; }
        
        [NotNull]
        public DateTime EndTime { get; set; }
        
        [NotNull]
        public Int32 TimeSpan { get; set; }
        
        [NotNull]
        public Decimal Category { get; set; }
        
    }
    
    
}
